### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [turboMaCk/aeson-combinators#27]
```
aeson-combinators              > Building library for aeson-combinators-0.0.5.0..
aeson-combinators              > [1 of 2] Compiling Data.Aeson.Combinators.Decode
aeson-combinators              >               
aeson-combinators              > /tmp/stack-d9db07aa05c3b14b/aeson-combinators-0.0.5.0/lib/Data/Aeson/Combinators/Decode.hs:348:27: error:
aeson-combinators              >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap a
aeson-combinators              >                      with: HS.HashMap Text a
aeson-combinators              >       Expected: Decoder (HS.HashMap Text a)
aeson-combinators              >         Actual: Decoder (Data.Aeson.KeyMap.KeyMap a)
aeson-combinators              >     • In the expression:
aeson-combinators              >         Decoder
aeson-combinators              >           $ \case
aeson-combinators              >               Object xs -> traverse d xs
aeson-combinators              >               val -> typeMismatch "Array" val
aeson-combinators              >       In an equation for ‘hashMapLazy’:
aeson-combinators              >           hashMapLazy (Decoder d)
aeson-combinators              >             = Decoder
aeson-combinators              >                 $ \case
aeson-combinators              >                     Object xs -> traverse d xs
aeson-combinators              >                     val -> typeMismatch "Array" val
aeson-combinators              >     • Relevant bindings include
aeson-combinators              >         d :: Value -> Parser a
aeson-combinators              >           (bound at lib/Data/Aeson/Combinators/Decode.hs:348:22)
aeson-combinators              >         hashMapLazy :: Decoder a -> Decoder (HS.HashMap Text a)
aeson-combinators              >           (bound at lib/Data/Aeson/Combinators/Decode.hs:348:1)
aeson-combinators              >     |         
aeson-combinators              > 348 | hashMapLazy (Decoder d) = Decoder $ \case
aeson-combinators              >     |                           ^^^^^^^^^^^^^^^...
aeson-combinators              >               
aeson-combinators              > /tmp/stack-d9db07aa05c3b14b/aeson-combinators-0.0.5.0/lib/Data/Aeson/Combinators/Decode.hs:357:29: error:
aeson-combinators              >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap a
aeson-combinators              >                      with: HS.HashMap Text a
aeson-combinators              >       Expected: Decoder (HS.HashMap Text a)
aeson-combinators              >         Actual: Decoder (Data.Aeson.KeyMap.KeyMap a)
aeson-combinators              >     • In the expression:
aeson-combinators              >         Decoder
aeson-combinators              >           $ \case
aeson-combinators              >               Object xs -> traverse d xs
aeson-combinators              >               val -> typeMismatch "Array" val
aeson-combinators              >       In an equation for ‘hashMapStrict’:
aeson-combinators              >           hashMapStrict (Decoder d)
aeson-combinators              >             = Decoder
aeson-combinators              >                 $ \case
aeson-combinators              >                     Object xs -> traverse d xs
aeson-combinators              >                     val -> typeMismatch "Array" val
aeson-combinators              >     • Relevant bindings include
aeson-combinators              >         d :: Value -> Parser a
aeson-combinators              >           (bound at lib/Data/Aeson/Combinators/Decode.hs:357:24)
aeson-combinators              >         hashMapStrict :: Decoder a -> Decoder (HS.HashMap Text a)
aeson-combinators              >           (bound at lib/Data/Aeson/Combinators/Decode.hs:357:1)
aeson-combinators              >     |         
aeson-combinators              > 357 | hashMapStrict (Decoder d) = Decoder $ \case
aeson-combinators              >     |                             ^^^^^^^^^^^^^^^...
aeson-combinators              >               
aeson-combinators              > /tmp/stack-d9db07aa05c3b14b/aeson-combinators-0.0.5.0/lib/Data/Aeson/Combinators/Decode.hs:404:26: error:
aeson-combinators              >     • Couldn't match expected type ‘Key’ with actual type ‘Text’
aeson-combinators              >     • In the second argument of ‘(.:)’, namely ‘t’
aeson-combinators              >       In the second argument of ‘(=<<)’, namely ‘v .: t’
aeson-combinators              >       In the expression: d =<< v .: t
aeson-combinators              >     |         
aeson-combinators              > 404 |   Object v -> d =<< v .: t
aeson-combinators              >     |                          ^
aeson-combinators              >               
aeson-combinators              > /tmp/stack-d9db07aa05c3b14b/aeson-combinators-0.0.5.0/lib/Data/Aeson/Combinators/Decode.hs:457:25: error:
aeson-combinators              >     • Couldn't match expected type ‘Text’ with actual type ‘Key’
aeson-combinators              >     • In the first argument of ‘key’, namely ‘txt’
aeson-combinators              >       In the expression: key txt
aeson-combinators              >       In an equation for ‘element’: element (Key txt) = key txt
aeson-combinators              >     |         
aeson-combinators              > 457 | element (Key txt) = key txt
aeson-combinators              >     |                         ^^^
```
